import { Ionicons } from "@expo/vector-icons";
import { Pressable, StyleSheet, Text, View } from "react-native";
import AppHeader from "../components/AppHeader";
import { ScreenSurface, SurfaceCard } from "../components/ScreenSurface";
import { useTheme } from "../theme/ThemeContext";

export default function CommunityScreen() {
  const { colors } = useTheme();
  const posts = [{ title: "서초역 2번 출구 앞 보도블록이 정리됐어요", meta: "서초동 · 12분 전", icon: "checkmark-circle-outline" as const }, { title: "이번 주 우리 동네 XP가 18% 늘었어요", meta: "동네모아 · 1시간 전", icon: "sparkles-outline" as const }, { title: "공원 안내판 상태를 함께 확인해 주세요", meta: "반포동 · 3시간 전", icon: "megaphone-outline" as const }];
  return <ScreenSurface><AppHeader title="커뮤니티" /><Text style={[styles.subtitle, { color: colors.muted }]}>우리 동네의 변화와 이야기를 한눈에 봐요.</Text><View style={styles.chips}><View style={[styles.activeChip, { backgroundColor: colors.green }]}><Text style={styles.activeChipText}>전체</Text></View><View style={[styles.chip, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.chipText, { color: colors.text }]}>소식</Text></View><View style={[styles.chip, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.chipText, { color: colors.text }]}>인증</Text></View></View><SurfaceCard style={[styles.xpCard, { backgroundColor: colors.surfaceRaised }]}><View style={styles.xpIcon}><Ionicons name="sparkles" size={22} color={colors.green} /></View><View style={styles.xpCopy}><Text style={[styles.xpTitle, { color: colors.text }]}>이번 주 커뮤니티 XP</Text><Text style={[styles.xpMeta, { color: colors.muted }]}>동네 주민 83명이 함께 참여했어요.</Text></View><Text style={[styles.xpValue, { color: colors.green }]}>73/100</Text></SurfaceCard><Text style={[styles.sectionTitle, { color: colors.text }]}>동네 소식</Text>{posts.map((post) => <SurfaceCard key={post.title} style={styles.post}><View style={[styles.postIcon, { backgroundColor: colors.greenSoft }]}><Ionicons name={post.icon} size={20} color={colors.green} /></View><View style={styles.postCopy}><Text style={[styles.postTitle, { color: colors.text }]}>{post.title}</Text><Text style={[styles.postMeta, { color: colors.muted }]}>{post.meta}</Text></View><Pressable accessibilityLabel="소식 더보기"><Ionicons name="ellipsis-horizontal" size={20} color={colors.muted} /></Pressable></SurfaceCard>)}</ScreenSurface>;
}

const styles = StyleSheet.create({ subtitle: { fontFamily: "WantedSansR", fontSize: 12, marginBottom: 15, paddingHorizontal: 2 }, chips: { flexDirection: "row", gap: 8 }, activeChip: { borderRadius: 999, paddingHorizontal: 16, paddingVertical: 8 }, activeChipText: { color: "#17310b", fontFamily: "WantedSansB", fontSize: 11 }, chip: { borderRadius: 999, borderWidth: 1, paddingHorizontal: 16, paddingVertical: 8 }, chipText: { fontFamily: "WantedSansB", fontSize: 11 }, xpCard: { alignItems: "center", flexDirection: "row", marginTop: 18 }, xpIcon: { alignItems: "center", borderRadius: 999, height: 46, justifyContent: "center", width: 46 }, xpCopy: { flex: 1, marginLeft: 11 }, xpTitle: { fontFamily: "WantedSansB", fontSize: 14 }, xpMeta: { fontFamily: "WantedSansR", fontSize: 10, marginTop: 4 }, xpValue: { fontFamily: "WantedSansB", fontSize: 15 }, sectionTitle: { fontFamily: "WantedSansB", fontSize: 19, marginTop: 24 }, post: { alignItems: "center", flexDirection: "row", marginTop: 10, padding: 13 }, postIcon: { alignItems: "center", borderRadius: 13, height: 42, justifyContent: "center", width: 42 }, postCopy: { flex: 1, marginLeft: 11 }, postTitle: { fontFamily: "WantedSansB", fontSize: 13, lineHeight: 18 }, postMeta: { fontFamily: "WantedSansR", fontSize: 10, marginTop: 4 } });
