import { Ionicons } from "@expo/vector-icons";
import { Pressable, StyleSheet, Text, View } from "react-native";
import AppHeader from "../components/AppHeader";
import { ScreenSurface, SurfaceCard } from "../components/ScreenSurface";
import { useTheme } from "../theme/ThemeContext";

export default function MapScreen() {
  const { colors } = useTheme();
  const pins = [{ top: "28%", left: "22%", label: "20m" }, { top: "42%", left: "66%", label: "80m" }, { top: "64%", left: "38%", label: "120m" }];
  return <ScreenSurface><AppHeader title="동네 지도" /><View style={styles.chips}><Pressable style={[styles.chip, { backgroundColor: colors.greenSoft }]}><Text style={[styles.chipText, { color: "#17310b" }]}>전체 미션</Text><Ionicons name="chevron-down" size={14} color="#17310b" /></Pressable><Pressable style={[styles.chip, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.chipText, { color: colors.text }]}>가까운 순</Text></Pressable><Pressable style={[styles.chip, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.chipText, { color: colors.text }]}>필터</Text></Pressable></View><View style={[styles.map, { backgroundColor: colors.surfaceRaised, borderColor: colors.border }]}><View style={[styles.road, styles.roadOne, { backgroundColor: colors.border }]} /><View style={[styles.road, styles.roadTwo, { backgroundColor: colors.border }]} /><View style={[styles.road, styles.roadThree, { backgroundColor: colors.border }]} /><View style={[styles.userPin, { backgroundColor: colors.blue }]}><Ionicons name="navigate" size={18} color="#fff" /></View>{pins.map((pin) => <View key={pin.label} style={[styles.pin, { top: pin.top as any, left: pin.left as any, backgroundColor: colors.green }]}><Ionicons name="location" size={16} color="#17310b" /><Text style={styles.pinText}>{pin.label}</Text></View>)}<Text style={[styles.mapCaption, { color: colors.muted }]}>서초구 · 현재 위치 기준</Text></View><SurfaceCard><View style={styles.cardHeader}><View><Text style={[styles.cardEyebrow, { color: colors.green }]}>가까운 미션</Text><Text style={[styles.cardTitle, { color: colors.text }]}>공유자전거 이동하기</Text><Text style={[styles.cardMeta, { color: colors.muted }]}>20m · 약 3분 · 20P</Text></View><Ionicons name="arrow-forward-circle" size={30} color={colors.green} /></View></SurfaceCard></ScreenSurface>;
}

const styles = StyleSheet.create({ chips: { flexDirection: "row", gap: 8, marginBottom: 12 }, chip: { alignItems: "center", borderRadius: 999, borderWidth: 1, flexDirection: "row", gap: 5, paddingHorizontal: 12, paddingVertical: 8 }, chipText: { fontFamily: "WantedSansB", fontSize: 11 }, map: { borderRadius: 22, borderWidth: 1, height: 390, overflow: "hidden", position: "relative" }, road: { opacity: 0.65, position: "absolute" }, roadOne: { height: 18, left: -40, right: -40, top: 155, transform: [{ rotate: "-16deg" }] }, roadTwo: { bottom: 80, height: 15, left: -20, right: -20, transform: [{ rotate: "25deg" }] }, roadThree: { bottom: -30, height: 17, left: 150, top: -20, transform: [{ rotate: "35deg" }] }, userPin: { alignItems: "center", borderColor: "rgba(255,255,255,0.8)", borderRadius: 999, borderWidth: 3, height: 44, justifyContent: "center", left: "46%", position: "absolute", top: "47%", width: 44 }, pin: { alignItems: "center", borderRadius: 999, height: 34, justifyContent: "center", position: "absolute", width: 34 }, pinText: { color: "#17310b", fontFamily: "WantedSansB", fontSize: 8, marginTop: -2 }, mapCaption: { bottom: 14, fontFamily: "WantedSansR", fontSize: 11, left: 16, position: "absolute" }, cardHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, cardEyebrow: { fontFamily: "WantedSansB", fontSize: 11 }, cardTitle: { fontFamily: "WantedSansB", fontSize: 17, marginTop: 4 }, cardMeta: { fontFamily: "WantedSansR", fontSize: 11, marginTop: 5 } });
