import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import AppHeader from "../components/AppHeader";
import { ScreenSurface, SurfaceCard } from "../components/ScreenSurface";
import { useTheme } from "../theme/ThemeContext";

const rewards = [
  { id: "coffee", category: "기프티콘", title: "동네 카페 아메리카노", detail: "제휴 카페 12곳에서 사용", price: "350P", icon: "cafe-outline" as const, color: "#d3944b" },
  { id: "profile", category: "프로필 꾸미기", title: "초록 동네 배지", detail: "프로필에 30일 동안 표시", price: "200P", icon: "leaf-outline" as const, color: "#77c84d" },
  { id: "discount", category: "가게 할인", title: "서초구 세탁 10% 할인", detail: "이번 달 제휴 매장에서 사용", price: "500P", icon: "pricetag-outline" as const, color: "#7d5dcc" },
];

export default function StoreScreen() {
  const { colors } = useTheme();
  const [category, setCategory] = useState("전체");
  const visibleRewards = category === "전체" ? rewards : rewards.filter((reward) => reward.category === category);
  return <ScreenSurface><AppHeader title="상점" /><View style={styles.balance}><View><Text style={[styles.balanceLabel, { color: colors.muted }]}>사용 가능한 퀘스트 보상</Text><Text style={[styles.balanceValue, { color: colors.text }]}>1,250 <Text style={[styles.balanceUnit, { color: colors.green }]}>P</Text></Text></View><View style={[styles.balanceIcon, { backgroundColor: colors.greenSoft }]}><Ionicons name="sparkles" size={23} color={colors.green} /></View></View><Text style={[styles.intro, { color: colors.muted }]}>미션을 완료하고 쌓은 포인트를 우리 동네 혜택으로 바꿔요.</Text><View style={styles.chips}>{["전체", "기프티콘", "프로필 꾸미기", "가게 할인"].map((item) => <Pressable key={item} onPress={() => setCategory(item)} style={[styles.chip, { backgroundColor: category === item ? colors.green : colors.surface, borderColor: category === item ? colors.green : colors.border }]}><Text style={[styles.chipText, { color: category === item ? "#17310b" : colors.text }]}>{item}</Text></Pressable>)}</View><Text style={[styles.sectionTitle, { color: colors.text }]}>추천 보상</Text>{visibleRewards.map((reward) => <SurfaceCard key={reward.id} style={styles.rewardCard}><View style={[styles.rewardIcon, { backgroundColor: reward.color + "26" }]}><Ionicons name={reward.icon} size={24} color={reward.color} /></View><View style={styles.rewardCopy}><View style={styles.rewardHeader}><Text style={[styles.rewardCategory, { color: colors.green }]}>{reward.category}</Text><Text style={[styles.rewardPrice, { color: colors.text }]}>{reward.price}</Text></View><Text style={[styles.rewardTitle, { color: colors.text }]}>{reward.title}</Text><Text style={[styles.rewardDetail, { color: colors.muted }]}>{reward.detail}</Text><Pressable style={[styles.rewardButton, { backgroundColor: colors.surfaceRaised }]}><Text style={[styles.rewardButtonText, { color: colors.green }]}>자세히 보기</Text><Ionicons name="arrow-forward" size={14} color={colors.green} /></Pressable></View></SurfaceCard>)}<SurfaceCard style={[styles.partnerCard, { backgroundColor: colors.surfaceRaised }]}><View style={[styles.partnerIcon, { backgroundColor: colors.greenSoft }]}><Ionicons name="storefront-outline" size={23} color={colors.green} /></View><View style={styles.partnerCopy}><Text style={[styles.partnerTitle, { color: colors.text }]}>우리 동네 제휴 가게</Text><Text style={[styles.partnerDetail, { color: colors.muted }]}>미션 포인트로 이용할 수 있는 혜택을 준비 중이에요.</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted} /></SurfaceCard></ScreenSurface>;
}

const styles = StyleSheet.create({ balance: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 4, paddingHorizontal: 2 }, balanceLabel: { fontFamily: "WantedSansR", fontSize: 12 }, balanceValue: { fontFamily: "WantedSansB", fontSize: 30, marginTop: 4 }, balanceUnit: { fontSize: 15 }, balanceIcon: { alignItems: "center", borderRadius: 999, height: 55, justifyContent: "center", width: 55 }, intro: { fontFamily: "WantedSansR", fontSize: 12, lineHeight: 18, marginTop: 8 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 17 }, chip: { borderRadius: 999, borderWidth: 1, paddingHorizontal: 11, paddingVertical: 8 }, chipText: { fontFamily: "WantedSansB", fontSize: 10 }, sectionTitle: { fontFamily: "WantedSansB", fontSize: 19, marginTop: 24 }, rewardCard: { flexDirection: "row", marginTop: 10, padding: 13 }, rewardIcon: { alignItems: "center", borderRadius: 15, height: 54, justifyContent: "center", width: 54 }, rewardCopy: { flex: 1, marginLeft: 12 }, rewardHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, rewardCategory: { fontFamily: "WantedSansB", fontSize: 10 }, rewardPrice: { fontFamily: "WantedSansB", fontSize: 13 }, rewardTitle: { fontFamily: "WantedSansB", fontSize: 14, marginTop: 5 }, rewardDetail: { fontFamily: "WantedSansR", fontSize: 10, marginTop: 4 }, rewardButton: { alignItems: "center", alignSelf: "flex-start", borderRadius: 999, flexDirection: "row", gap: 5, marginTop: 9, paddingHorizontal: 10, paddingVertical: 6 }, rewardButtonText: { fontFamily: "WantedSansB", fontSize: 10 }, partnerCard: { alignItems: "center", flexDirection: "row", marginTop: 14 }, partnerIcon: { alignItems: "center", borderRadius: 13, height: 42, justifyContent: "center", width: 42 }, partnerCopy: { flex: 1, marginLeft: 10 }, partnerTitle: { fontFamily: "WantedSansB", fontSize: 13 }, partnerDetail: { fontFamily: "WantedSansR", fontSize: 10, lineHeight: 15, marginTop: 3 } });
