import { Ionicons } from "@expo/vector-icons";
import { Image } from "expo-image";
import { Pressable, StyleSheet, Text, View } from "react-native";
import AppHeader from "../components/AppHeader";
import { ScreenSurface, SurfaceCard } from "../components/ScreenSurface";
import { useTheme } from "../theme/ThemeContext";

export default function MissionScreen() {
  const { colors } = useTheme();
  const steps = ["해당 위치로 이동하기", "공유자전거 상태 확인하기", "사진 촬영하기", "미션 제출하기"];
  return <ScreenSurface><AppHeader title="미션 상세" back /><View style={[styles.hero, { backgroundColor: colors.greenSoft }]}><View style={styles.heroTop}><Text style={styles.eyebrow}>근처 미션 · 100m</Text><Text style={styles.points}>★ 20P</Text></View><Text style={styles.heroTitle}>공유자전거 이동하기</Text><Text style={styles.heroMeta}>공공질서 · temp_username</Text><View style={styles.heroFooter}><Text style={styles.heroMeta}>약 3분 소요</Text><Ionicons name="bookmark-outline" size={20} color="#17310b" /></View></View><View style={styles.metaRow}><SurfaceCard style={styles.metaCard}><Ionicons name="location-outline" size={20} color={colors.green} /><Text style={[styles.metaValue, { color: colors.text }]}>100m</Text><Text style={[styles.metaLabel, { color: colors.muted }]}>거리</Text></SurfaceCard><SurfaceCard style={styles.metaCard}><Ionicons name="people-outline" size={20} color={colors.purple} /><Text style={[styles.metaValue, { color: colors.text }]}>2명</Text><Text style={[styles.metaLabel, { color: colors.muted }]}>참여 중</Text></SurfaceCard><SurfaceCard style={styles.metaCard}><Ionicons name="calendar-outline" size={20} color={colors.blue} /><Text style={[styles.metaValue, { color: colors.text }]}>8.10</Text><Text style={[styles.metaLabel, { color: colors.muted }]}>마감일</Text></SurfaceCard></View><Text style={[styles.sectionTitle, { color: colors.text }]}>미션 설명</Text><Text style={[styles.body, { color: colors.muted }]}>지정된 위치에 있는 공유자전거를 보행에 방해되지 않는 구역으로 옮겨주세요. 주변 보행자의 동선을 먼저 확인하고 안전하게 진행해요.</Text><Text style={[styles.sectionTitle, { color: colors.text }]}>미션 단계</Text><SurfaceCard>{steps.map((step, index) => <View key={step} style={styles.step}><View style={[styles.stepNumber, { backgroundColor: index === 0 ? colors.green : colors.surfaceRaised }]}><Text style={[styles.stepNumberText, { color: index === 0 ? "#17310b" : colors.muted }]}>{index + 1}</Text></View><Text style={[styles.stepText, { color: index === 0 ? colors.green : colors.text }]}>{step}</Text>{index === 0 && <Ionicons name="chevron-forward" size={17} color={colors.green} />}</View>)}</SurfaceCard><Text style={[styles.sectionTitle, { color: colors.text }]}>참고 예시</Text><View style={styles.referenceRow}>{["omg.png", "omg.png", "omg.png"].map((image, index) => <View key={`${image}-${index}`} style={styles.reference}><Image source={require("@/assets/images/omg.png")} style={styles.referenceImage} /><View style={[styles.referenceBadge, { backgroundColor: index === 0 ? colors.green : "#d95d4d" }]}><Ionicons name={index === 0 ? "checkmark" : "close"} size={14} color="#fff" /></View></View>)}</View><Pressable style={[styles.cta, { backgroundColor: colors.green }]}><Text style={styles.ctaText}>미션 시작하기</Text><Ionicons name="arrow-forward" size={18} color="#17310b" /></Pressable></ScreenSurface>;
}

const styles = StyleSheet.create({ hero: { borderRadius: 20, padding: 17 }, heroTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, eyebrow: { color: "#2c461c", fontFamily: "WantedSansB", fontSize: 12 }, points: { color: "#24310e", fontFamily: "WantedSansB", fontSize: 14 }, heroTitle: { color: "#050505", fontFamily: "WantedSansB", fontSize: 23, marginTop: 14 }, heroMeta: { color: "#4a603c", fontFamily: "WantedSansR", fontSize: 12, marginTop: 5 }, heroFooter: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginTop: 16 }, metaRow: { flexDirection: "row", gap: 8, marginTop: 12 }, metaCard: { flex: 1, padding: 11 }, metaValue: { fontFamily: "WantedSansB", fontSize: 16, marginTop: 10 }, metaLabel: { fontFamily: "WantedSansR", fontSize: 10, marginTop: 2 }, sectionTitle: { fontFamily: "WantedSansB", fontSize: 18, marginTop: 22 }, body: { fontFamily: "WantedSansR", fontSize: 13, lineHeight: 21, marginTop: 7 }, step: { alignItems: "center", flexDirection: "row", minHeight: 43 }, stepNumber: { alignItems: "center", borderRadius: 999, height: 26, justifyContent: "center", width: 26 }, stepNumberText: { fontFamily: "WantedSansB", fontSize: 12 }, stepText: { flex: 1, fontFamily: "WantedSansR", fontSize: 13, marginLeft: 10 }, referenceRow: { flexDirection: "row", gap: 10, marginTop: 10 }, reference: { flex: 1, position: "relative" }, referenceImage: { borderRadius: 14, height: 94, width: "100%" }, referenceBadge: { alignItems: "center", borderRadius: 999, bottom: 7, height: 22, justifyContent: "center", position: "absolute", right: 7, width: 22 }, cta: { alignItems: "center", borderRadius: 999, flexDirection: "row", gap: 8, justifyContent: "center", marginTop: 22, paddingVertical: 14 }, ctaText: { color: "#17310b", fontFamily: "WantedSansB", fontSize: 15 } });
