import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";
import AppHeader from "../components/AppHeader";
import { ScreenSurface, SurfaceCard } from "../components/ScreenSurface";
import { useTheme } from "../theme/ThemeContext";

export default function MyScreen() {
  const router = useRouter();
  const { colors } = useTheme();
  const stats = [{ icon: "star-outline" as const, value: "1,250", label: "총 포인트", color: colors.orange }, { icon: "checkmark-circle-outline" as const, value: "24", label: "미션 완료", color: colors.green }, { icon: "people-outline" as const, value: "12", label: "참여 일수", color: colors.purple }, { icon: "flame-outline" as const, value: "5", label: "연속 참여", color: colors.orange }];
  return <ScreenSurface><AppHeader title="마이페이지" settings /><View style={styles.profile}><View style={[styles.avatar, { backgroundColor: colors.greenSoft }]}><Ionicons name="person" size={28} color={colors.green} /></View><View style={styles.profileCopy}><Text style={[styles.username, { color: colors.text }]}>temp_username</Text><Text style={[styles.location, { color: colors.muted }]}>서초구 주민 · Gold</Text></View><Ionicons name="chevron-forward" size={19} color={colors.muted} /></View><SurfaceCard style={styles.statsCard}><View style={styles.statsGrid}>{stats.map((stat, index) => <View key={stat.label} style={[styles.stat, index < 3 && { borderRightColor: colors.border, borderRightWidth: 1 }]}><Ionicons name={stat.icon} size={20} color={stat.color} /><Text style={[styles.statValue, { color: colors.text }]}>{stat.value}</Text><Text style={[styles.statLabel, { color: colors.muted }]}>{stat.label}</Text></View>)}</View></SurfaceCard><View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.text }]}>배지</Text><Text style={[styles.more, { color: colors.green }]}>더보기 ›</Text></View><SurfaceCard><View style={styles.badges}>{["첫 미션", "환경 지킴이", "기록자"].map((badge, index) => <View key={badge} style={styles.badge}><View style={[styles.badgeIcon, { backgroundColor: index === 1 ? colors.greenSoft : colors.surfaceRaised }]}><Ionicons name={index === 0 ? "location" : index === 1 ? "leaf" : "camera"} size={24} color={index === 1 ? colors.green : colors.orange} /></View><Text style={[styles.badgeText, { color: colors.text }]}>{badge}</Text><Text style={[styles.badgeDate, { color: colors.muted }]}>2026.07.{20 + index * 4}</Text></View>)}</View></SurfaceCard><View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.text }]}>활동 요약</Text><Text style={[styles.more, { color: colors.green }]}>최근 4주</Text></View><SurfaceCard><View style={styles.activityRows}>{["미션 완료", "동네 제보", "커뮤니티 XP"].map((label, index) => <View key={label} style={styles.activityRow}><View style={styles.activityLabel}><Ionicons name={index === 0 ? "checkmark-circle-outline" : index === 1 ? "megaphone-outline" : "sparkles-outline"} size={18} color={colors.green} /><Text style={[styles.activityText, { color: colors.text }]}>{label}</Text></View><Text style={[styles.activityValue, { color: colors.text }]}>{["24개", "8건", "73 XP"][index]}</Text></View>)}</View></SurfaceCard><View style={styles.sectionHeader}><Text style={[styles.sectionTitle, { color: colors.text }]}>내가 저장한 미션</Text><Pressable onPress={() => router.push("/mission")}><Text style={[styles.more, { color: colors.green }]}>3개 ›</Text></Pressable></View><SurfaceCard><Text style={[styles.savedTitle, { color: colors.text }]}>공원 안내판 상태 확인하기</Text><Text style={[styles.savedMeta, { color: colors.muted }]}>180m · 약 2분 · 5P</Text></SurfaceCard></ScreenSurface>;
}

const styles = StyleSheet.create({ profile: { alignItems: "center", flexDirection: "row", marginBottom: 14, paddingHorizontal: 4 }, avatar: { alignItems: "center", borderRadius: 999, height: 62, justifyContent: "center", width: 62 }, profileCopy: { flex: 1, marginLeft: 13 }, username: { fontFamily: "WantedSansB", fontSize: 17 }, location: { fontFamily: "WantedSansR", fontSize: 11, marginTop: 4 }, statsCard: { padding: 12 }, statsGrid: { flexDirection: "row" }, stat: { alignItems: "center", flex: 1, minHeight: 74, paddingHorizontal: 2 }, statValue: { fontFamily: "WantedSansB", fontSize: 16, marginTop: 8 }, statLabel: { fontFamily: "WantedSansR", fontSize: 9, marginTop: 3, textAlign: "center" }, sectionHeader: { alignItems: "baseline", flexDirection: "row", justifyContent: "space-between", marginTop: 22, paddingHorizontal: 2 }, sectionTitle: { fontFamily: "WantedSansB", fontSize: 18 }, more: { fontFamily: "WantedSansB", fontSize: 11 }, badges: { flexDirection: "row", justifyContent: "space-between" }, badge: { alignItems: "center", flex: 1 }, badgeIcon: { alignItems: "center", borderRadius: 999, height: 54, justifyContent: "center", width: 54 }, badgeText: { fontFamily: "WantedSansB", fontSize: 10, marginTop: 8 }, badgeDate: { fontFamily: "WantedSansR", fontSize: 8, marginTop: 3 }, activityRows: { gap: 16 }, activityRow: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, activityLabel: { alignItems: "center", flexDirection: "row", gap: 8 }, activityText: { fontFamily: "WantedSansR", fontSize: 13 }, activityValue: { fontFamily: "WantedSansB", fontSize: 13 }, savedTitle: { fontFamily: "WantedSansB", fontSize: 14 }, savedMeta: { fontFamily: "WantedSansR", fontSize: 11, marginTop: 5 } });
